import type { ProjectListItem } from '../types/api'

export const MOCK_PROJECTS: ProjectListItem[] = [
  {
    project_id: 'demo_project',
    name: 'DirectorLoop — Demo Reel',
    description: 'AI rough cut with self-healing critic loop. Gemini indexed 47 scenes.',
    status: 'active',
    progress: 72,
    updated_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    thumbnail_type: 'timeline',
    starred: true,
  },
  {
    project_id: 'scout_ios',
    name: 'Scout — iOS',
    description: 'Mobile app walkthrough video. 12 screen recordings imported.',
    status: 'draft',
    progress: 0,
    updated_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    thumbnail_type: 'mobile',
    starred: false,
  },
  {
    project_id: 'fitsync',
    name: 'FitSync',
    description: 'Product demo for FitSync dashboard. Narration pending TTS generation.',
    status: 'draft',
    progress: 30,
    updated_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    thumbnail_type: 'analytics',
    starred: false,
  },
  {
    project_id: 'gameify',
    name: 'Gameify',
    description: 'Explainer video for gamification SDK. B-roll generation queued.',
    status: 'active',
    progress: 45,
    updated_at: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    thumbnail_type: 'gameloop',
    starred: false,
  },
  {
    project_id: 'untitled_project',
    name: 'Untitled Project',
    description: 'Empty project. No footage imported yet.',
    status: 'empty',
    progress: 0,
    updated_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    thumbnail_type: 'empty',
    starred: false,
  },
]
